apiVersion: v1
kind: PodTemplate
metadata:
  name: test-ace
  annotations:
    k8srun.yashkov.org/prefix: test
    k8srun.yashkov.org/instance: ace
template:
  metadata:
    labels:
      app.kubernetes.io/name: test-app
      app.kubernetes.io/component: job
      app.kubernetes.io/managed-by: k8srun
  spec:
    restartPolicy: Never
    volumes:
      - name: temp
        emptyDir:
          sizeLimit: 100Mi
    containers:
      - name: job
        image: alpine:latest
        imagePullPolicy: Always
        command: []
        env:
          - name: JOB_TEMP
            value: /var/run/k8srun
        volumeMounts:
          - mountPath: /var/run/k8srun
            name: temp
        resources:
          limits:
            cpu: 500m
            memory: 800Mi
          requests:
            cpu: 50m
            memory: 800Mi
